name: bgc-argo-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  # The core Python and Jupyter environment
  - python=3.11
  - jupyterlab
  - notebook
  
  # Data manipulation and math
  - pandas
  - numpy

  # Oceanographic calculations
  - gsw
  
  # Plotting and mapping
  - matplotlib
  - cartopy
  
  # NetCDF data handling (Crucial for Argo)
  - xarray
  - netcdf4
  - dask
  
  # Pip installer and specific pip packages
  - pip
  - pip:
      - ipynb