name: Daily Argo Dashboard

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:      # Allows you to run it manually for testing

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas numpy plotly xarray netCDF4 requests nbconvert ipykernel ipynb

      - name: Run Notebook
        run: |
          # This runs your notebook and generates the index.html file
          jupyter nbconvert --to notebook --execute automation/chla_weekly.ipynb

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ 
          publish_branch: gh-pages
          force_orphan: true # This prevents the 600MB history bloat!
